---
name: Docs

on:
  push:
    branches:
      - main
  release:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: pip install -r docs/requirements.txt
      - run: mkdocs gh-deploy --force