name: test_scripts

on:
  workflow_dispatch:

jobs:

  unitTestBWE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: pip install -r test/requirements.txt
      - run: python test/script_unit_test_BWE.py
      
  unitTestPBWE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: pip install -r test/requirements.txt
      - run: python test/script_unit_test_PBWE.py
      
  unitTestSSBWE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: pip install -r test/requirements.txt
      - run: python test/script_unit_test_SSBWE.py
      
  integrationTestBWE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: pip install -r test/requirements.txt
      - run: python test/script_integration_test_BWE.py
      
  integrationTestPBWE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: pip install -r test/requirements.txt
      - run: python test/script_integration_test_PBWE.py
      
  integrationTestSSBWE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: pip install -r test/requirements.txt
      - run: python test/script_integration_test_SSBWE.py

  perfoTestBWE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: pip install -r test/requirements.txt
      - run: python test/script_test_performances_white_noise_BWE.py 
      - uses: actions/upload-artifact@v4
        with:
          name: BWE_test_report
          path: test/PyBWE_Report_test_performances_white_noise.md
          
  perfoTestSSBWE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: pip install -r test/requirements.txt
      - run: python test/script_test_performances_white_noise_SSBWE.py
      - uses: actions/upload-artifact@v4
        with:
          name: SSBWE_test_report
          path: test/PySSBWE_Report_test_performances_white_noise.md
          
  perfoTestPBWE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: pip install -r test/requirements.txt
      - run: python test/script_test_performances_white_noise_PBWE.py 
      - uses: actions/upload-artifact@v4
        with:
          name: PBWE_test_report
          path: test/PyPBWE_Report_test_performances_white_noise.md