on:
  push:
    branches:
      - main
  release:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install -r docs/requirements.txt
      - run: python test/script_test_performances_white_noise_BWE.py 
      