on:
  push:
    branches:
      - main
  release:
    branches:
      - main

jobs:

  unitTestBWE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install -r test/requirements.txt
      - run: python test/script_unit_test_BWE.py
      
  unitTestPBWE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install -r test/requirements.txt
      - run: python test/script_unit_test_PBWE.py

  perfoTestBWE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install -r test/requirements.txt
      - run: python test/script_test_performances_white_noise_BWE.py 
      - uses: actions/upload-artifact@v1
        with:
          name: BWE_test_report
          path: test/PyBWE_Report_test_performances_white_noise.md
          
  perfoTestSSBWE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install -r test/requirements.txt
      - run: python test/script_test_performances_white_noise_SSBWE.py
      - uses: actions/upload-artifact@v1
        with:
          name: SSBWE_test_report
          path: test/PySSBWE_Report_test_performances_white_noise.md
          
  perfoTestPBWE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install -r test/requirements.txt
      - run: python test/script_test_performances_white_noise_PBWE.py 
      - uses: actions/upload-artifact@v1
        with:
          name: PBWE_test_report
          path: test/PyPBWE_Report_test_performances_white_noise.md